name: Google Ad Grants
favicon: null
layout_spectrum: 0.4985
typography_spectrum: 0.13196
title: adgrants.info
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59862159-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dd4330'
    - '#009e55'
    - '#f6b500'
    - '#ffffff'
    - '#050403'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
